Fix AttributeError when TEST_DATA_ROOT_PATH is set (#8047)
Initiate a Path object from TEST_DATA_ROOT_PATH to fix the error:
AttributeError: 'str' object has no attribute 'mkdir'