[µTVM] apps: Fix Zephyr code example for STM32F746 boards (#7772)
Commit c39a6e25d "Clean up uTVM demo runtime, add ONNX model test and
tutorial (#7557)" changed the location of the Zephyr code example to
apps/ so this commit updates the tutorial examples under tutorials/micro
to reflect the new location where src/main.c resides.

Since commit c39a6e25d also split Zephyr configuration per boards,
under project's boards/, this commit also adds a proper config for the
STM32F746 Discovery board and fixes a nit in the comment in
boards/nucleo_f746zg.conf. It also removes CONFIG_MAIN_STACK_SIZE=50 for
disco and nucleo boards since the MCUs for both boads are Cortex-m7
based, not Contex-m33.

For the new boards/stm32f746g_disco.conf CONFIG_TEST_RANDOM_GENERATOR=y
is set, otherwise when CONFIG_ENTROPY_GENERATOR=y linking will fail
with the following error:

rand32.h:33: undefined reference to `z_impl_sys_rand32_get'

Finally, the size of 'uart_data' temporary buffer is reduced a bit (to
8 bytes) to free some additional bytes in SRAM, since most MCUs have a
1-byte FIFO, like it happens with Cortex-M-based MCUs.

Signed-off-by: Gustavo Romero <gustavo.romero@linaro.org>